[versions]
gcp-bom = "26.0.0"
jackson = "2.15.2"
kotlin = "1.9.10"
ktor = "2.3.3"
ktlint = "0.50.0"
kotest = "5.6.2"
cucumber = "7.12.0"
mockk = "1.13.4"
junit-platform-suite = "1.9.3" #relatert til cucumber
kotlinx-coroutines-slf4j = "1.7.1"
dagpenger-biblioteker = "2023.01.16-10.20.e8450fdff15a"
testContainer = "1.19.0"

[libraries]
dp-biblioteker-oauth2-klient = { group = "com.github.navikt.dp-biblioteker", name = "oauth2-klient", version = "2023.04.27-09.33.fcf0798bf943" }
dp-biblioteker-image-utils = { group = "com.github.navikt.dp-biblioteker", name = "image-utils", version = "2023.04.27-09.33.fcf0798bf943" }
konfig = { group = "com.natpryce", name = "konfig", version = "1.6.10.0" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
ktor-client-auth-jvm = { group = "io.ktor", name = "ktor-client-auth-jvm", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-jackson = { group = "io.ktor", name = "ktor-client-jackson", version.ref = "ktor" }
ktor-client-logging-jvm = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor" }
ktor-client-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-server = { group = "io.ktor", name = "ktor-server", version.ref = "ktor" }
ktor-server-test-host-jvm = { group = "io.ktor", name = "ktor-server-test-host-jvm", version.ref = "ktor" }
ktor-server-auth-jvm = { group = "io.ktor", name = "ktor-server-auth-jvm", version.ref = "ktor" }
ktor-server-auth-jwt = { group = "io.ktor", name = "ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-jackson = { group = "io.ktor", name = "ktor-serialization-jackson", version.ref = "ktor" }
ktor-server-logging-jvm = { group = "io.ktor", name = "ktor-server-call-logging-jvm", version.ref = "ktor" }
mock-oauth2-server = { group = "no.nav.security", name = "mock-oauth2-server", version = "1.0.0" }
aktivitetslogg = { group = "no.nav.dagpenger", name = "aktivitetslogg", version = "20230831.52f628" }


# Database
flywaydb = { group = "org.flywaydb", name = "flyway-core", version = "9.21.2" }
postgresql-driver = { group = "org.postgresql", name = "postgresql", version = "42.6.0" }
hikariCP = { group = "com.zaxxer", name = "HikariCP", version = "5.0.1" }
kotlinquery = { group = "com.github.seratch", name = "kotliquery", version = "1.9.0" }
testContainer = { group = "org.testcontainers", name = "testcontainers", version.ref = "testContainer" }
testContainer-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testContainer" }


jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jackson-annotation = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
jackson-blackbird = { group = "com.fasterxml.jackson.module", name = "jackson-module-blackbird", version.ref = "jackson" }

urnlib = { group = "de.slub-dresden", name = "urnlib", version = "2.0.1" }
rapids-and-rivers = { group = "com.github.navikt", name = "rapids-and-rivers", version = "2023080113411690890096.310ed8e5ed93" }
kotlin-logging = { group = "io.github.microutils", name = "kotlin-logging", version = "3.0.5" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "6.21.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

[bundles]
ktor-server = ["ktor-server", "ktor-server-auth-jvm", "ktor-server-auth-jwt", "ktor-server-content-negotiation", "ktor-serialization-jackson", "ktor-server-logging-jvm", "jackson-datatype-jsr310"]
ktor-client = ["ktor-client-auth-jvm", "ktor-client-cio", "ktor-serialization-jackson", "ktor-client-logging-jvm", "ktor-client-content-negotiation"]
jackson = ["jackson-core", "jackson-datatype-jsr310", "jackson-annotation", "jackson-module-kotlin"]
postgres = ["flywaydb", "postgresql-driver", "hikariCP", "kotlinquery"]
postgres-test = ["testContainer", "testContainer-postgresql"]