name: Build and deploy

on: [push]

env:
  IMAGE: ghcr.io/${{ github.repository }}/dp-vedtak:${{ github.sha }}


jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: --configuration-cache build installDist

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          context: mediator
#          tags: ${{ env.IMAGE }}
#          push: true
#          cache-from: type=gha
#          cache-to: type=gha,mode=max


#  deploy-dev:
#    name: Deploy to dev
#    needs: [build]
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Fetch NAIS yaml
#        uses: actions/download-artifact@v1
#        with:
#          name: nais-yaml
#          path: nais
#
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-gcp
#          RESOURCE: nais/nais.yaml
#          VARS: nais/dev-vars.yaml
#          PRINT_PAYLOAD: true
#
#  deploy-prod:
#    name: Deploy to Production
#    needs: [build]
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Fetch NAIS yaml
#        uses: actions/download-artifact@v1
#        with:
#          name: nais-yaml
#          path: nais
#
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: prod-gcp
#          RESOURCE: nais/nais.yaml
#          VARS: nais/prod-vars.yaml
#          PRINT_PAYLOAD: true